# Generated by Django 4.2 on 2023-05-05 19:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0002_post_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="user",
            new_name="owner",
        ),
    ]
