# Generated by Django 4.2 on 2023-05-06 08:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0003_rename_user_post_owner"),
    ]

    operations = [
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name="post",
            name="comment",
            field=models.ManyToManyField(to="posts.comment"),
        ),
    ]
